services:
  wallet-service:
    build: . 
    container_name: wallet_api
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - redis
      - fraud-api

  celery-worker:
    build: . 
    container_name: celery_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    restart: on-failure

  fraud-api:
    build: ./FRAUD_DETECTION_API
    container_name: fraud_detector
    ports:
      - "8001:8001"
    restart: on-failure
    environment:
      - PYTHONPATH=.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    depends_on:
      - redis

  db:
    image: postgres:15-alpine
    container_name: db-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Zuzul2024@#
      - POSTGRES_DB=wallet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: