global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds locally

scrape_configs:
  - job_name: "wallet-api-metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["wallet-service:8000"]